"""Tests for the generated Roam wiring denominator."""

from __future__ import annotations

import pytest

from scripts import build_wiring_coverage as coverage


def test_unclassified_roam_command_fails_closed() -> None:
    classifications = {
        "known": coverage.CommandClassification(
            edit_relevant=True,
            failure_classes=("F3",),
            reason="The fixture command resolves callers before an edit.",
        )
    }

    with pytest.raises(coverage.CoverageError, match="unclassified Roam command.*new-command"):
        coverage.validate_classifications(frozenset({"known", "new-command"}), classifications)


def test_channel_command_outside_inventory_fails_closed() -> None:
    with pytest.raises(coverage.CoverageError, match="CONTEXT references commands outside"):
        coverage.validate_channels(
            frozenset({"known"}),
            {
                "CONTEXT": frozenset({"known", "removed-command"}),
                "VERIFY": frozenset({"known"}),
                "HOOK": frozenset({"known"}),
                "MCP": frozenset({"known"}),
            },
        )


def test_checked_in_classification_covers_resolved_roam() -> None:
    coverage.validate_classifications(coverage.roam_command_inventory(), coverage.COMMAND_CLASSIFICATION)


def test_render_starts_with_generated_by_header() -> None:
    report = coverage.CoverageReport(
        roam_version="99.0.0",
        inventory=frozenset({"known"}),
        channels={
            "CONTEXT": frozenset({"known"}),
            "VERIFY": frozenset(),
            "HOOK": frozenset(),
            "MCP": frozenset(),
        },
        classifications={
            "known": coverage.CommandClassification(
                edit_relevant=True,
                failure_classes=("F3",),
                reason="The fixture command resolves callers before an edit.",
            )
        },
    )

    rendered = coverage.render_markdown(report)

    assert rendered.startswith("<!-- Generated by scripts/build_wiring_coverage.py; do not edit. -->\n")
    assert "Roam 99.0.0" in rendered
    assert "`known`" in rendered


def test_verify_derives_product_check_registration_and_trigger_descriptions() -> None:
    inventory = coverage.roam_command_inventory()

    assert coverage._product_verify_commands(inventory) == frozenset({"py-types", "rules"})

    import compile_code.cli as cli

    descriptions = dict(cli._VERIFY_AUTO_CHECK_REGISTRY)
    assert "Any edit" in descriptions["rules"]
    assert "not_applicable" in descriptions["rules"]
    assert "Python edits" in descriptions["py-types"]
    assert "pre-edit type surface" in descriptions["py-types"]
    assert "absolute legacy debt never gates" in descriptions["py-types"]
    assert cli._auto_select_product_verify_checks(["README.md"]) == ("rules", "py-types")
    assert cli._auto_select_product_verify_checks(["tests/test_service.py"]) == ("rules", "py-types")
    assert cli._auto_select_product_verify_checks([]) == ()
