"""Tests for the generated Roam wiring denominator."""

from __future__ import annotations

import pytest

from scripts import build_wiring_coverage as coverage


def test_unclassified_roam_command_fails_closed() -> None:
    classifications = {
        "known": coverage.CommandClassification(
            edit_relevant=True,
            failure_classes=("F3",),
            reason="The fixture command resolves callers before an edit.",
        )
    }

    with pytest.raises(coverage.CoverageError, match="unclassified Roam command.*new-command"):
        coverage.validate_classifications(frozenset({"known", "new-command"}), classifications)


def test_channel_command_outside_inventory_fails_closed() -> None:
    with pytest.raises(coverage.CoverageError, match="CONTEXT references commands outside"):
        coverage.validate_channels(
            frozenset({"known"}),
            {
                "CONTEXT": frozenset({"known", "removed-command"}),
                "VERIFY": frozenset({"known"}),
                "HOOK": frozenset({"known"}),
                "MCP": frozenset({"known"}),
            },
        )


def test_checked_in_classification_covers_resolved_roam() -> None:
    coverage.validate_classifications(coverage.roam_command_inventory(), coverage.COMMAND_CLASSIFICATION)


def test_render_starts_with_generated_by_header() -> None:
    report = coverage.CoverageReport(
        roam_version="99.0.0",
        inventory=frozenset({"known"}),
        channels={
            "CONTEXT": frozenset({"known"}),
            "VERIFY": frozenset(),
            "HOOK": frozenset(),
            "MCP": frozenset(),
        },
        classifications={
            "known": coverage.CommandClassification(
                edit_relevant=True,
                failure_classes=("F3",),
                reason="The fixture command resolves callers before an edit.",
            )
        },
    )

    rendered = coverage.render_markdown(report)

    assert rendered.startswith("<!-- Generated by scripts/build_wiring_coverage.py; do not edit. -->\n")
    assert "Roam 99.0.0" in rendered
    assert "`known`" in rendered


def test_verify_derives_product_check_registration_and_trigger_descriptions() -> None:
    inventory = coverage.roam_command_inventory()

    assert coverage._product_verify_commands(inventory) == frozenset(
        {
            "calc-golden",
            "collapse",
            "orphan-imports",
            "py-modern",
            "py-types",
            "rules",
            "stale-refs",
            "tx-boundaries",
        }
    )

    import compile_code.cli as cli

    descriptions = dict(cli._VERIFY_AUTO_CHECK_REGISTRY)
    assert "Any edit" in descriptions["rules"]
    assert "not_applicable" in descriptions["rules"]
    assert "Python edits" in descriptions["py-types"]
    assert "pre-edit type surface" in descriptions["py-types"]
    assert "absolute legacy debt never gates" in descriptions["py-types"]
    assert "Python edits" in descriptions["py-modern"]
    assert "Git pre-edit state" in descriptions["py-modern"]
    assert "absolute legacy debt never gates" in descriptions["py-modern"]
    assert ".roam/calc-golden" in descriptions["calc-golden"]
    assert "Git pre-edit" in descriptions["calc-golden"]
    assert "Python and JavaScript/TypeScript edits" in descriptions["collapse"]
    assert "Git pre-edit state" in descriptions["collapse"]
    assert "absolute legacy debt never gates" in descriptions["collapse"]
    assert "Transaction-relevant Python and JavaScript/TypeScript edits" in descriptions["tx-boundaries"]
    assert "Git pre-edit state" in descriptions["tx-boundaries"]
    assert "absolute legacy defects never gate" in descriptions["tx-boundaries"]
    assert "deleted or renamed" in descriptions["orphan-imports"]
    assert "import lines" in descriptions["orphan-imports"]
    assert "Git pre-edit state" in descriptions["orphan-imports"]
    assert "Deleted or renamed paths" in descriptions["stale-refs"]
    assert "referenced by other tracked files" in descriptions["stale-refs"]
    assert "Git pre-edit state" in descriptions["stale-refs"]
    assert cli._auto_select_product_verify_checks(["README.md"]) == (
        "rules",
        "py-types",
        "py-modern",
        "calc-golden",
        "stale-refs",
    )
    assert cli._auto_select_product_verify_checks(["tests/test_service.py"]) == (
        "rules",
        "py-types",
        "py-modern",
        "calc-golden",
        "collapse",
        "tx-boundaries",
        "orphan-imports",
        "stale-refs",
    )
    assert cli._auto_select_product_verify_checks(["web/service.tsx"]) == (
        "rules",
        "py-types",
        "py-modern",
        "calc-golden",
        "collapse",
        "tx-boundaries",
        "orphan-imports",
        "stale-refs",
    )
    assert "collapse" not in cli._auto_select_product_verify_checks(["scripts/check.sh"])
    assert cli._auto_select_product_verify_checks([]) == ()


def test_f10_review_declares_the_detector_gate_complete() -> None:
    report = coverage.build_report()

    assert "tx-boundaries" in report.channels["VERIFY"]
    assert coverage._failure_state(report, "F10") == ("covered", 3, 3)
    migration_plan = report.classifications["migration-plan"]
    assert migration_plan.edit_relevant is False
    assert migration_plan.failure_classes == ()
    assert "planning ACTION" in migration_plan.reason


def test_f8_review_declares_both_reference_gates_complete() -> None:
    report = coverage.build_report()

    assert {"delete-check", "stale-refs"} <= report.channels["VERIFY"]
    assert coverage._failure_state(report, "F8") == ("covered", 2, 2)
    safe_delete = report.classifications["safe-delete"]
    assert safe_delete.edit_relevant is False
    assert safe_delete.failure_classes == ()
    assert "planning ACTION" in safe_delete.reason
